---

- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted
  tags:
    - tweaks

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u -k all
  tags:
    - tuning
