---

- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted
  tags:
    - tweaks

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u -k all
  tags:
    - tuning

- name: Reload ssh
  ansible.builtin.service:
    name: ssh
    state: reloaded
  tags:
    - hardening

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  tags:
    - hardening

- name: Reload pve-firewall
  ansible.builtin.service:
    name: pve-firewall
    state: reloaded
  tags:
    - hardening
