---
# main tasks for proxmox

- name: Include bootstrap
  ansible.builtin.include_tasks: bootstrap.yml
  tags:
    - bootstrap

- name: Include upgrade
  ansible.builtin.include_tasks: upgrade.yml
  tags:
    - upgrade

- name: Include tweaks
  ansible.builtin.include_tasks: tweaks.yml
  tags:
    - tweaks
